name: Docker Image CI

env:
  REGISTRY: ${{ vars.REGISTRY }} 
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  CACHE_IMAGE: ${{ vars.REGISTRY }}/${{ github.repository }}:cache
  GIT_SHA: ${{ github.sha }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - run: echo ${GIT_SHA}
      
    - name: Login to Ali Docker
      uses: docker/login-action@v2
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/arm64,linux/amd64
        tags: ${{ vars.REGISTRY }}/ulfg-face-detection:v${{ env.GIT_SHA }}
        cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}
        cache-to: type=registry,ref=${{ env.CACHE_IMAGE }},mode=max
